### ISSUE TITLE
There was an error running

### ISSUE THREAD

**Issue by zhaosonghui** [GeWu-Lab/Ref-AVS#6]
Congratulations! This is an exciting piece of work! When I was reproducing this work, I encountered an error：

>>> File arch:
./data/REFAVS
    - /media
    - /gt_mask
    - /metadata.csv

>>> Sys: set "CUDA_VISIBLE_DEVICES" - GPU: 0
/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/transformers/utils/deprecation.py:165: UserWarning: The following named arguments are not valid for `Mask2FormerImageProcessorForRefAVS.__init__` and were ignored: '_max_size'
  return func(*args, **kwargs)
>>> Init m2f for refavs...
{'train_params': ['audio_proj', 'text_proj', 'prompt_proj', 'avs_adapt', 'ref_avs_attn'], 'text_model': 'distilbert/distilroberta-base', 'checkpoint': None, 'save_ckpt': '/home/zh/Ref-AVS-main/trained_ckpts/refavs', 'log_path': '/home/zh/Ref-AVS-main/log/ckpt_rec.txt', 'data_dir': '/home/zh/Ref-AVS-main/data/REFAVS', 'show_params': True, 'm2f_model': 'facebook/mask2former-swin-base-ade-semantic', 'lr': 0.0001, 'epochs': 50, 'loss': 'bce', 'train': False, 'val': 'val', 'test': True, 'gpu_id': '0', 'run': 'train', 'frame_n': 10, 'text_max_len': 25}
/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/transformers/utils/deprecation.py:165: UserWarning: The following named arguments are not valid for `Mask2FormerImageProcessor.__init__` and were ignored: '_max_size'
  return func(*args, **kwargs)
Traceback (most recent call last):
  File "/home/zh/Ref-AVS-main/run_refavs.py", line 132, in <module>
    run(m2f_avs)
  File "/home/zh/Ref-AVS-main/run_refavs.py", line 22, in run
    train_dataset = REFAVS('train', args)
  File "/home/zh/Ref-AVS-main/datasets/dataset_refavs.py", line 45, in __init__
    pipe.input('path')
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/pipeline.py", line 101, in output
    run_pipe.preload()
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 153, in preload
    return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool, TimeProfiler(False))
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 67, in __init__
    self._initialize()
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 83, in _initialize
    raise RuntimeError(node.err_msg)
RuntimeError: Node-audio-embedding/vggish-1 runs failed, error msg: Create audio-embedding/vggish-1 operator audio-embedding/vggish:main with args None and kws None failed, err: libtorch_hip.so: cannot open shared object file: No such file or directory, Traceback (most recent call last):
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 106, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag, latest)
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 154, in load_operator
    op = factory(function, arg, kws, tag, latest)
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 137, in _load_operator_from_hub
    return self._load_operator_from_path(path, function, arg, kws, tag)
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 120, in _load_operator_from_path
    op = self._load_op(modname, path, fname)
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 79, in _load_op
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zh/.towhee/operators/audio-embedding/vggish/versions/main/__init__.py", line 15, in <module>
    from .vggish import Vggish
  File "/home/zh/.towhee/operators/audio-embedding/vggish/versions/main/vggish.py", line 32, in <module>
    import vggish_input
  File "/home/zh/.towhee/operators/audio-embedding/vggish/versions/main/vggish_input.py", line 20, in <module>
    import torchaudio
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/torchaudio/_extension.py", line 27, in <module>
    _init_extension()
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/torchaudio/_extension.py", line 21, in _init_extension
    torch.ops.load_library(path)
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/zh/anaconda3/envs/refavs/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_hip.so: cannot open shared object file: No such file or directory

**Comment by yaotingwangofficial** [comment]
``` log
File "/home/zh/Ref-AVS-main/datasets/dataset_refavs.py", line 45, in init
pipe.input('path')
File "/home/zh/anaconda3/envs/refavs/lib/python3.9/site-packages/towhee/runtime/pipeline.py", line 101, in output
run_pipe.preload()
```
Please check the towhee version you used, for others they did not meet this problem with towhee. Check this issue: https://github.com/GeWu-Lab/Ref-AVS/issues/2 

If you still find the towhee is of problem, I would encourage you use the following code from Google Colab: [link](https://colab.research.google.com/drive/1r_8OnmwXKwmH0n4RxBfuICVBgpbJt_Fs?usp=sharing#scrollTo=MJWFPPSoAQzF).
